# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\cvVideoCapture.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cvVideoCapture(object):
    def setupUi(self, cvVideoCapture):
        cvVideoCapture.setObjectName("cvVideoCapture")
        cvVideoCapture.resize(824, 643)
        self.layoutWidget = QtWidgets.QWidget(cvVideoCapture)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 802, 620))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.opencvFrameLabel = QtWidgets.QLabel(self.layoutWidget)
        self.opencvFrameLabel.setMinimumSize(QtCore.QSize(800, 500))
        self.opencvFrameLabel.setObjectName("opencvFrameLabel")
        self.gridLayout.addWidget(self.opencvFrameLabel, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 1, 1, 1)
        self.autocalibrateColor = QtWidgets.QPushButton(self.layoutWidget)
        self.autocalibrateColor.setObjectName("autocalibrateColor")
        self.gridLayout_3.addWidget(self.autocalibrateColor, 1, 0, 1, 1)
        self.useFilter = QtWidgets.QPushButton(self.layoutWidget)
        self.useFilter.setObjectName("useFilter")
        self.gridLayout_3.addWidget(self.useFilter, 1, 1, 1, 1)
        self.colorSettings = QtWidgets.QPushButton(self.layoutWidget)
        self.colorSettings.setObjectName("colorSettings")
        self.gridLayout_3.addWidget(self.colorSettings, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(13, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 0, 1, 1)

        self.retranslateUi(cvVideoCapture)
        QtCore.QMetaObject.connectSlotsByName(cvVideoCapture)

    def retranslateUi(self, cvVideoCapture):
        _translate = QtCore.QCoreApplication.translate
        cvVideoCapture.setWindowTitle(_translate("cvVideoCapture", "Form"))
        self.opencvFrameLabel.setText(_translate("cvVideoCapture", "TextLabel"))
        self.label_2.setText(_translate("cvVideoCapture", "Настройка цвета"))
        self.label.setText(_translate("cvVideoCapture", "Фильтр"))
        self.autocalibrateColor.setText(_translate("cvVideoCapture", "Автокалибровка"))
        self.useFilter.setText(_translate("cvVideoCapture", "Использовать фильтр"))
        self.colorSettings.setText(_translate("cvVideoCapture", "Ручная настройка"))
