# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\cvVideoCapture.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cvVideoCapture(object):
    def setupUi(self, cvVideoCapture):
        cvVideoCapture.setObjectName("cvVideoCapture")
        cvVideoCapture.resize(832, 628)
        self.widget = QtWidgets.QWidget(cvVideoCapture)
        self.widget.setGeometry(QtCore.QRect(10, 10, 802, 597))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.opencvFrameLabel = QtWidgets.QLabel(self.widget)
        self.opencvFrameLabel.setMinimumSize(QtCore.QSize(800, 500))
        self.opencvFrameLabel.setObjectName("opencvFrameLabel")
        self.gridLayout.addWidget(self.opencvFrameLabel, 0, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.autocalibrateColor = QtWidgets.QPushButton(self.widget)
        self.autocalibrateColor.setObjectName("autocalibrateColor")
        self.verticalLayout.addWidget(self.autocalibrateColor)
        self.colorSettings = QtWidgets.QPushButton(self.widget)
        self.colorSettings.setObjectName("colorSettings")
        self.verticalLayout.addWidget(self.colorSettings)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)

        self.retranslateUi(cvVideoCapture)
        QtCore.QMetaObject.connectSlotsByName(cvVideoCapture)

    def retranslateUi(self, cvVideoCapture):
        _translate = QtCore.QCoreApplication.translate
        cvVideoCapture.setWindowTitle(_translate("cvVideoCapture", "Form"))
        self.opencvFrameLabel.setText(_translate("cvVideoCapture", "TextLabel"))
        self.label_2.setText(_translate("cvVideoCapture", "Настройка цвета"))
        self.autocalibrateColor.setText(_translate("cvVideoCapture", "Автокалибровка"))
        self.colorSettings.setText(_translate("cvVideoCapture", "Ручная настройка"))
