# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\cvVideoCapture.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cvVideoCapture(object):
    def setupUi(self, cvVideoCapture):
        cvVideoCapture.setObjectName("cvVideoCapture")
        cvVideoCapture.resize(688, 645)
        self.widget = QtWidgets.QWidget(cvVideoCapture)
        self.widget.setGeometry(QtCore.QRect(30, 20, 627, 611))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.opencvFrameLabel1 = QtWidgets.QLabel(self.widget)
        self.opencvFrameLabel1.setMinimumSize(QtCore.QSize(500, 300))
        self.opencvFrameLabel1.setObjectName("opencvFrameLabel1")
        self.verticalLayout.addWidget(self.opencvFrameLabel1)
        self.opencvFrameLabel2 = QtWidgets.QLabel(self.widget)
        self.opencvFrameLabel2.setMinimumSize(QtCore.QSize(500, 300))
        self.opencvFrameLabel2.setObjectName("opencvFrameLabel2")
        self.verticalLayout.addWidget(self.opencvFrameLabel2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 2, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.autoCalibrateColor = QtWidgets.QPushButton(self.widget)
        self.autoCalibrateColor.setObjectName("autoCalibrateColor")
        self.verticalLayout_2.addWidget(self.autoCalibrateColor)
        self.colorSettings = QtWidgets.QPushButton(self.widget)
        self.colorSettings.setObjectName("colorSettings")
        self.verticalLayout_2.addWidget(self.colorSettings)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)

        self.retranslateUi(cvVideoCapture)
        QtCore.QMetaObject.connectSlotsByName(cvVideoCapture)

    def retranslateUi(self, cvVideoCapture):
        _translate = QtCore.QCoreApplication.translate
        cvVideoCapture.setWindowTitle(_translate("cvVideoCapture", "Form"))
        self.opencvFrameLabel1.setText(_translate("cvVideoCapture", "TextLabel"))
        self.opencvFrameLabel2.setText(_translate("cvVideoCapture", "TextLabel"))
        self.label_3.setText(_translate("cvVideoCapture", "Настройки цвета"))
        self.autoCalibrateColor.setText(_translate("cvVideoCapture", "Автокалибровка"))
        self.colorSettings.setText(_translate("cvVideoCapture", "Ручная настройка"))
