# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\registrationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_registrationWin(object):
    def setupUi(self, registrationWin):
        registrationWin.setObjectName("registrationWin")
        registrationWin.resize(410, 169)
        self.widget = QtWidgets.QWidget(registrationWin)
        self.widget.setGeometry(QtCore.QRect(30, 10, 351, 142))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.opName = QtWidgets.QLineEdit(self.widget)
        self.opName.setObjectName("opName")
        self.gridLayout.addWidget(self.opName, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.opSecName = QtWidgets.QLineEdit(self.widget)
        self.opSecName.setObjectName("opSecName")
        self.gridLayout.addWidget(self.opSecName, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.opProton = QtWidgets.QLineEdit(self.widget)
        self.opProton.setObjectName("opProton")
        self.gridLayout.addWidget(self.opProton, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.login = QtWidgets.QPushButton(self.widget)
        self.login.setObjectName("login")
        self.gridLayout.addWidget(self.login, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)

        self.retranslateUi(registrationWin)
        QtCore.QMetaObject.connectSlotsByName(registrationWin)

    def retranslateUi(self, registrationWin):
        _translate = QtCore.QCoreApplication.translate
        registrationWin.setWindowTitle(_translate("registrationWin", "Form"))
        self.label_3.setText(_translate("registrationWin", "Отчество:"))
        self.label.setText(_translate("registrationWin", "Фамилия:"))
        self.label_2.setText(_translate("registrationWin", "Имя:"))
        self.login.setText(_translate("registrationWin", "Войти"))
        self.label_4.setText(_translate("registrationWin", "ОКНО РЕГИСТРАЦИИ"))
